name: Build Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: environment-win-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: "Windows x64 MSVC"
            artifact: "Windows-MSVC.tar.xz"
            build_type: "RelWithDebInfo"
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            cc: "cl"
            cxx: "cl"
            archiver: "7z a"
            generators: "Visual Studio 17 2022"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup
        id: setup
        uses: Silverlan/common_actions/setup@main
          
      - name: Download binaries
        uses: Silverlan/common_actions/download_build_binaries@main
        continue-on-error: true

      - name: Build Dynamic Library
        id: build-dynamic
        uses: Silverlan/util_udm/github_actions/build@master
        with:
          repo-directory: '${{ github.workspace }}'
          build_shared: '1'
          build-directory: './build_dynamic'
          
      - name: Build Static Library
        id: build-static
        uses: Silverlan/util_udm/github_actions/build@master
        with:
          repo-directory: '${{ github.workspace }}'
          build_shared: '0'
          build-directory: './build_static'
          
      - name: Create Release Files
        shell: bash
        run: |
          mkdir release

          mkdir release/lib
          cp build_static/${{ matrix.config.build_type }}/util_udm.lib release/lib/util_udm.lib

          mkdir release/bin
          cp build_dynamic/${{ matrix.config.build_type }}/util_udm.dll release/bin/util_udm.dll
          cp build_dynamic/${{ matrix.config.build_type }}/util_udm.lib release/bin/util_udm.lib

          # find . -type f -name "*.dll" -exec cp {} release/bin/ \;
          # find . -type f -name "*.lib" -exec cp {} release/lib/ \;
          
      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
